version: '3.8'

services:
  wordcount:
    image: wordcount
    container_name: "word_count"
    build: .
    command: uvicorn FastAPI.app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db


  textfile:
    image: text_file
    container_name: "text_file"
    build: .
    command: uvicorn docker.app.main:app --host 0.0.0.0 --port 8086
    volumes:
      - logs:/code/
    ports:
      - 8086:8086
    expose:
      - 8086


  db:
    image: postgres:12.0-alpine
    container_name: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=fastapi_db
    expose:
      - 5432

  redis:
    container_name: sentry-redis
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'


volumes:
  postgres_data:
  logs:
  redis-data: